spring:
  application:
    name: healthCheck_API

  datasource:
    url: jdbc:mysql://localhost:3307/mydb?useTimezone=true&serverTimezone=UTC
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      format_sql: true
  database-platform: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: false
    baseline-on-migrate: false
    locations: classpath:db/migration
    validate-on-migrate: false

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

security:
  enabled: true
  jwt:
    token:
      secret-key: my-very-secure-secret-key-with-at-least-32-chars
      expire-lenght: 3600000
      issuer: health-check-system
      access-expire-length: 3600000 # 1h
      refresh-expire-length: 2592000000 # 30d

cors:
  originPatterns: http://localhost:8080,http://localhost:3000

logging:
  config:
    classpath: src/main/resources/log4j2.xml

server:
  port: 8080