spring:
  application:
    name: healthCheck_API

  datasource:
    url: jdbc:mysql://localhost:3307/mydb?useTimezone=true&serverTimezone=UTC
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  properties:
    hibernate:
      format_sql: true
  database-platform: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000

cors:
  originPatterns: http://localhost:8080,http://localhost:3000

logging:
  config:
    classpath: src/main/resources/log4j2.xml

server:
  port: 8080